poto_masuv
KonstantinYevchuk/Filmoteca_team_project pull request #13
Opened 2023-01-26 15:59 UTC by RuslanTenderyts

2023-01-26 17:13 UTC, Orest-M requested changes
В position назви позицій пишуться в лапках, це строки. Назви напиши з великих па виправ одруки (Scrum Master, Team Lead) 
Імена перепиши, будь-ласка, англійською
1 - Orest Mykhalchuk
2 - Konstantin Yevchuk
3 - EugeneTitov
4 - Olexander Yanchenko
5 - Sergiy Maxymchuk
6 - Alexey Ryzhenko
7 - Ruslan Tenderyts
8 - Vladyslav Rohalov
9 - Svitlana Kozachenko
10 - Volodymyr Zankevych
11 - Olexandr Kutsenko
12 - Viacheslav Borysov
13 - Yuriy Grechyha

2023-01-27 11:48 UTC, RuslanTenderyts commented
поправив

2023-01-27 13:21 UTC, Titotrapatonni approved these changes

2023-01-27 15:10 UTC, KonstantinYevchuk approved these changes

2023-01-27 15:11 UTC, Orest-M approved these changes

2023-01-27 15:37 UTC, merged