add functions getFetch
KonstantinYevchuk/Filmoteca_team_project pull request #2
Opened 2023-01-24 22:51 UTC by Titotrapatonni

2023-01-24 23:08 UTC, Titotrapatonni commented
Не додав опис: функції повертають проміс (массив обєктів) вже з колекцією фільмів. Використовувати додатковий then не потрібно. Додам цей опис у файл, коли буду додавати перевірку на помилки 404 та ін.

2023-01-25 07:21 UTC, KonstantinYevchuk commented
Жень поменяй Throw new error на консоль лог

2023-01-25 07:26 UTC, KonstantinYevchuk reviewed
Исправь пожалуйста пункты

2023-01-25 07:26 UTC, KonstantinYevchuk commented on src/js/fetch-films.js
> +    throw new Error(error);
поменяй пожалуйста на консоль лог

2023-01-25 07:26 UTC, KonstantinYevchuk commented on src/js/fetch-films.js
> +    throw new Error(error);
и тут

2023-01-25 07:30 UTC, Orest-M requested changes
Когда мы прописываем throw new Error, это создаёт ошибку, которая останавивает весь наш код. Поэтому просто консоль ложим ошибку

2023-01-25 09:21 UTC, Titotrapatonni commented
Замінив прокидування помилки на консоль лог помилки в блоці catch

2023-01-25 09:33 UTC, KonstantinYevchuk approved these changes

2023-01-25 09:35 UTC, Orest-M approved these changes

2023-01-25 09:36 UTC, merged